### ISSUE TITLE
MSSQL error when updating entity

### ISSUE THREAD

**Issue by helderco** [slickframework/orm#3]
When using MSSQL, an entity update throws an error, most likely because the primary key is being included in the fields do update.

```
An error occurred when querying the database service.SQL: 
UPDATE table SET (..., id = :id, ...) WHERE table.id = :id
Error: SQLSTATE[HY000]: General error: 102 General SQL Server error: Check messages from the SQL Server [102] (severity 15) [(null)] Database error: (null) [0] (severity 0) []
```

**Comment by silvamfilipe** [comment]
@helderco  it seems that you are using `IDENTITY` field type as primary key.
This is a specific data type of MS SQL and it is immutable, thats why it fails when executing `UPDATE` queries.

Nevertheless it makes no sense to change the primary key of an entity so I also thing it is a good idea to remove the primary of the list of data to be updated.

Thanks @helderco

**Comment by silvamfilipe** [comment]
Primary key was removed from the field list to be updated.
